spring:
  security:
    oauth2:
      resourceserver:
        jwt:
#          issuer-uri: http://localhost:8082/realms/selmag
          jwk-set-uri: http://localhost:8082/realms/selmag/protocol/openid-connect/certs
          # Отключаем iss проверку, потому что host должен быть одинаковый, это не возможно с docker
          # docker http://host.docker.internal:8082

      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/selmag
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            scope:
              - metrics
            client-id: admin-service
            client-secret: M9cPE609ncufTtMeaICp55BJL5inRZ3K
          login:
            # authorization-grant-type: authorization_code default
            provider: keycloak
            scope:
              - metrics
              - openid
            client-id: admin-service
            client-secret: M9cPE609ncufTtMeaICp55BJL5inRZ3K
          discovery:
            provider: keycloak
            client-id: admin-service
            client-secret: M9cPE609ncufTtMeaICp55BJL5inRZ3K
            authorization-grant-type: client_credentials
            scope:
              - discovery

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true # можно убрать регистрацию admin server в самом себе через eureka
  instance:
    prefer-ip-address: true